---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: rabbitmq-management-ingress
  namespace: rabbitmq
spec:
  rules:
  - host: ${SERVICE_URL}
    http:
      paths:
      - backend:
          serviceName: rabbitmq-service
          servicePort: 80
  - host: ${MANAGEMENT_URL}
    http:
      paths:
      - backend:
          serviceName: rabbitmq-management
          servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: rabbitmq
  labels:
    app: rabbitmq
spec:
  ports:
    - name: rabbitmq-service
      port: 80
      targetPort: 5672
  selector:     
    app: rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-management
  namespace: rabbitmq
  labels:
    app: rabbitmq
spec:
  ports:
    - name: rabbitmq-management
      port: 80
      targetPort: 15672
  selector:     
    app: rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: rabbitmq
  labels:
    app: rabbitmq
spec:
  clusterIP: None
  ports:
  - port: 5672
    name: amqp
  selector:
    app: rabbitmq
