FROM nginx:1.15.0-alpine

RUN apk --update --no-cache add tzdata \                                                                                
        && ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \                                                    
        && echo "Asia/Shanghai" > /etc/timezone
